### ISSUE TITLE
DQN

### ISSUE THREAD

**Issue by guofeng97** [ArkS0001/CloudSim#1]
I want to know which part should be modified specifically if the task scheduling of DQN is implemented？

**Comment by ArkS0001** [comment]
We have few options while working on reinforcement agents, we still have not worked upon Deep Q
But have implemented Q learning,SARSA,Whale, Genetic and also successfully made hybrids.
Just by simply creating a scheduler and feeding it with cloudletlist and vm list for parameters like mips, length,size etc 
And then passing it through the algorithms,should generate some data,of fitness or somekind of info like Qtable, population index. Use it to for further allocation.
